config/routes.rb
require 'sidekiq/web'

Searchapp03::Application.routes.draw do
  get "/search", to: 'search#index', as: 'search'

  resources :authorships

  resources :authors

  resources :categories

  root to: 'articles#index'
  resources :articles do
    collection { get :search }
  end

  mount Sidekiq::Web => '/sidekiq'

end

app/models/article.rb
class Article < ActiveRecord::Base
  has_and_belongs_to_many :categories, after_add:    [ lambda { |a,c| Indexer.perform_async(:update,  a.class.to_s, a.id) } ],
                                       after_remove: [ lambda { |a,c| Indexer.perform_async(:update,  a.class.to_s, a.id) } ]

  has_many                :authorships
  has_many                :authors, through: :authorships
  has_many                :comments


  include Searchable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.page(params[:page])
  end

    # GET /articles/search
  def search
    @articles = Article.search(params[:q]).page(params[:page]).records

    render action: "index"
  end

  # GET /articles/1

  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render action: 'show', status: :created, location: @article }
      else
        format.html { render action: 'new' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content, :published_on)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :published_on %><br>
    <%= f.date_select :published_on %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/_search_form.html.erb
<hr>

<%= form_tag search_articles_path, method: 'get' do %>
  <div class="input-group">
  <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search...' %>

  <span class="input-group-btn">
    <button type="button" class="btn btn-default">
      <span class="glyphicon glyphicon-search"></span>
    </button>
  </span>
</div>

<% end %>

<hr>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1><%= controller.action_name == 'search' ? 'Searching articles' : 'Listing articles' %></h1>

<%= render partial: 'search_form' %>


<table class="table table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Published on</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.__send__ controller.action_name == 'search' ? :each_with_hit : :each do |article, hit| %>
      <tr>
        <td><%= hit.try(:highlight).try(:title)   ? hit.highlight.title.join.html_safe : article.title %></td>
        <td><%= hit.try(:highlight).try(:content) ? hit.highlight.content.join('&hellip;').html_safe : article.content %></td>
        <td><%= article.published_on %></td>
        <td style="width: 50px"><%= link_to 'Show', article , class: 'btn btn-default btn-xs'%></td>
        <td style="width: 50px"><%= link_to 'Edit', edit_article_path(article) , class: 'btn btn-default btn-xs'%></td>
        <td style="width: 50px"><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-default btn-xs'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @articles %>


<hr>

<p style="text-align: center; margin-bottom: 21px">
  <%= link_to 'New Article',  new_article_path %>, class: 'btn btn-primary btn-xs', style: 'color: #fff'
<%= link_to 'All articles', articles_path if params[:q] %>, class: 'btn btn-primary btn-xs', style: 'color: #fff'


</p>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @article.published_on %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>