config/routes.rb
require 'sidekiq/web'

Searchapp03::Application.routes.draw do
  get "/search", to: 'search#index', as: 'search'

  resources :authorships

  resources :authors

  resources :categories

  root to: 'articles#index'
  resources :articles do
    collection { get :search }
  end

  mount Sidekiq::Web => '/sidekiq'

end

app/models/authorship.rb
class Authorship < ActiveRecord::Base
  belongs_to :article, touch: true

  belongs_to :author
end

app/controllers/authorships_controller.rb
class AuthorshipsController < ApplicationController
  before_action :set_authorship, only: [:show, :edit, :update, :destroy]

  # GET /authorships
  # GET /authorships.json
  def index
    @authorships = Authorship.all
  end

  # GET /authorships/1
  # GET /authorships/1.json
  def show
  end

  # GET /authorships/new
  def new
    @authorship = Authorship.new
  end

  # GET /authorships/1/edit
  def edit
  end

  # POST /authorships
  # POST /authorships.json
  def create
    @authorship = Authorship.new(authorship_params)

    respond_to do |format|
      if @authorship.save
        format.html { redirect_to @authorship, notice: 'Authorship was successfully created.' }
        format.json { render action: 'show', status: :created, location: @authorship }
      else
        format.html { render action: 'new' }
        format.json { render json: @authorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorships/1
  # PATCH/PUT /authorships/1.json
  def update
    respond_to do |format|
      if @authorship.update(authorship_params)
        format.html { redirect_to @authorship, notice: 'Authorship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @authorship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorships/1
  # DELETE /authorships/1.json
  def destroy
    @authorship.destroy
    respond_to do |format|
      format.html { redirect_to authorships_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authorship
      @authorship = Authorship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authorship_params
      params.require(:authorship).permit(:article_id, :author_id)
    end
end

app/helpers/authorships_helper.rb
module AuthorshipsHelper
end

app/views/authorships/_form.html.erb
<%= form_for(@authorship) do |f| %>
  <% if @authorship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authorship.errors.count, "error") %> prohibited this authorship from being saved:</h2>

      <ul>
      <% @authorship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article_id %><br>
    <%= f.text_field :article_id %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.text_field :author_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorships/edit.html.erb
<h1>Editing authorship</h1>

<%= render 'form' %>

<%= link_to 'Show', @authorship %> |
<%= link_to 'Back', authorships_path %>

app/views/authorships/index.html.erb
<h1>Listing authorships</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Author</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @authorships.each do |authorship| %>
      <tr>
        <td><%= authorship.article %></td>
        <td><%= authorship.author %></td>
        <td><%= link_to 'Show', authorship %></td>
        <td><%= link_to 'Edit', edit_authorship_path(authorship) %></td>
        <td><%= link_to 'Destroy', authorship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authorship', new_authorship_path %>

app/views/authorships/new.html.erb
<h1>New authorship</h1>

<%= render 'form' %>

<%= link_to 'Back', authorships_path %>

app/views/authorships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @authorship.article %>
</p>

<p>
  <strong>Author:</strong>
  <%= @authorship.author %>
</p>

<%= link_to 'Edit', edit_authorship_path(@authorship) %> |
<%= link_to 'Back', authorships_path %>